name: Generate Code Images

on:
  push:
    paths:
      - "scripts/**/*.py"
  pull_request:
    paths:
      - "scripts/**/*.py"

jobs:
  generate-images:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to commit output files

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Shallow clone for faster checkout

      - name: Set Up Python
        id: setup_python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"  

      - name: Cache Virtual Environment
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: ./.venv/
          key: ${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-venv-${{ hashFiles('.github/scripts/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-venv-

      - name: Install Dependencies
        shell: bash
        run: |
          python -m venv ./.venv
          source ./.venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r .github/scripts/requirements_image.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'  # Only install if cache is missing

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: scripts/**/*.py

      - name: Generate Code Images
        if: steps.changed-files.outputs.any_changed == 'true'
        shell: bash
        run: |
          source ./.venv/bin/activate
          python scripts/generate_images.py || exit 1

      - name: Commit and Push Generated Images
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add generated_images/
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-generated code images"
          git push
