name: Rename Miscellaneous Files in OTHER

on:
  push:
    paths:
      - "OTHER/**"  # Trigger only when files in OTHER/ change
  pull_request:
    paths:
      - "OTHER/**"

jobs:
  rename-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to commit renamed files

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Shallow clone for faster checkout

      - name: Set Up Python
        id: setup_python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"  

      - name: Cache Virtual Environment
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: ./.venv/
          key: ${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-venv-${{ hashFiles('.github/scripts/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-venv-

      - name: Install Dependencies
        shell: bash
        run: |
          python -m venv ./.venv
          source ./.venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r .github/scripts/requirements.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'  # Only install if cache is missing

      - name: Get Changed Files in OTHER/
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: OTHER/**

      - name: Run File Renaming Script
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        shell: bash
        run: |
          source ./.venv/bin/activate
          python .github/scripts/rename_other_files.py || exit 1

      - name: Commit and Push Renamed Files
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add OTHER/
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-renamed miscellaneous files in OTHER/"
          git push
