name: Run Python Scripts

on:
  push:
    paths:
      - "scripts/**/*.py"  # Only trigger when Python files in 'scripts/' change
  pull_request:
    paths:
      - "scripts/**/*.py"

jobs:
  analyze-and-run:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to commit output files

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Shallow clone for faster checkout

      - name: Set Up Python
        id: setup_python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"  # Use Python 3.9

      - name: Cache Virtual Environment
        id: cache-venv
        uses: actions/cache@v3
        with:
          path: ./.venv/
          key: ${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-venv-${{ hashFiles('.github/scripts/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-venv-

      - name: Install Dependencies
        shell: bash
        run: |
          python -m venv ./.venv
          source ./.venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r .github/scripts/requirements.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'  # Only install if cache is missing

      - name: Install Repo Project
        shell: bash
        run: |
          source ./.venv/bin/activate
          python -m pip install -U -e ./python  # Ensure local project dependencies are installed

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: scripts/**/*.py
          
      - name: Run Analysis and Execute Scripts
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        shell: bash
        run: |
          source ./.venv/bin/activate
          python .github/scripts/analyze_and_run.py || exit 1

      - name: Commit and Push Output Files
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add output/
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-generated output for new scripts"
          git push
