name: Run Python Scripts

on:
  push:
    paths:
      - "scripts/**/*.py"  # Only trigger when Python files in 'scripts/' change
  pull_request:
    paths:
      - "scripts/**/*.py"

jobs:
  analyze-and-run:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to commit output files

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Shallow clone for faster checkout

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"  # Specify exact version for faster setup
          cache: "pip"  # Enable pip caching

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai
        
      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: scripts/**/*.py
          
      - name: Run Analysis and Execute Scripts
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python .github/scripts/analyze_and_run.py || exit 1

      - name: Commit and Push Output Files
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add output/
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-generated output for new scripts"
          git push
