name: Run Python Scripts

on:
  push:
    paths:
      - "scripts/**/*.py"  # Trigger only on Python file changes
  pull_request:
    paths:
      - "scripts/**/*.py"

jobs:
  analyze-and-run:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to commit output files

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Install Dependencies
        run: pip install openai

      - name: Identify Modified Scripts
        id: find_scripts
        run: |
          MODIFIED_FILES=$(git diff --name-only HEAD^ HEAD -- 'scripts/**/*.py' | jq -R -s -c 'split("\n")[:-1]')
          echo "files=$MODIFIED_FILES" >> $GITHUB_ENV

      - name: Run Analysis in Parallel
        if: env.files != "[]"
        run: |
          echo "$files" | jq -r '.[]' | xargs -P 4 -I {} python .github/scripts/analyze_and_run.py {}

      - name: Commit and Push Output Files
        if: env.files != "[]"
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add output/
          git diff --cached --quiet || (git commit -m "Auto-generated output for new scripts" && git push)
