name: Run P2 Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Python script with input
        run: |
          script -q -c "echo 'pap' | python PRACTICALS/P2.py" /dev/stdout > output.txt

      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: python-output
          path: output.txt
